### ISSUE TITLE
Generating injection annotations support

### ISSUE THREAD

**Issue by jakoss** [s0nicyouth/kmapper#4]
My idea here is that we can enable generating code for automatic injection using Hilt/Anvil/Koin.

This option would be hidden after ksp flag.

So for koin we would just generate `@Single` or `@Factory` for mapper and be done with it.

For Hilt we can generate module that will bind the mapper with interface and add `@Inject` to mapper constructor itself.

For Anvil we can add `@Inject` to mapper constructor and `@ContributesBinding(scope = AppScope::class)` to mapper type (`AppScope` qualified name will have to be set by user via ksp flag)

What do you think about this? I could contribute with the solution here

**Comment by s0nicyouth** [comment]
@jakoss The idea is good as far as I can see it. And PR are always welcome. The only thing that seems crucial here to me is that Hilt/Anvil/Koin generators should reside in separate modules so that user can choose what they really want to use and to keep them as decoupled as possible.

**Comment by jakoss** [comment]
@s0nicyouth I did some research and there is no need for a separate module (and there is no need to do that). Instead I'll create a ksp flag. By default it won't generate anything, but user might want to set it to something like "Koin". Then if the flag is set i'll just add new annotation. There is no need to even use direct dependency, I'll just generate additional line of code and that's it :)

**Comment by s0nicyouth** [comment]
@jakoss I didn't quite get how exactly you want to make it work to be honest. Could you please give concrete code examples of how it would work?

**Comment by jakoss** [comment]
I'll send you a link with implementation for Koin tomorrow (hopefully)
I have the generating implemented, the only thing missing are tests and sample app

**Comment by jakoss** [comment]
I think koin is not handling ksp multiple round processing correctly, after the first run they just stop processing alltogether. I created a ticket with that: https://github.com/InsertKoinIO/koin-annotations/issues/66

Anyway, the generation itself seems to working fine, i can proceed with anvil and hilt i think. I'll do a PR to koin if needed. You can see example of usage here: https://github.com/jakoss/kmapper/blob/feature/di-integration/examples/koin/src/main/kotlin/com/syouth/kmapper/koin/Main.kt

All user have to do is to pass ksp option, like this: https://github.com/jakoss/kmapper/blob/feature/di-integration/examples/koin/build.gradle.kts and the annotations will be generated.

Processor changes are very simple, you can see those in this commit here: https://github.com/jakoss/kmapper/commit/95cb56e873306af8eb5ea72329954c114894e247

**Comment by s0nicyouth** [comment]
@jakoss Ok but I'm still not sure if putting it into processor module is a good idea as I think it would be nice to have addons as separate as possible(see Room for example, it has support for RxJava and so on implemented as separate module). My concern here is that it gets too coupled and hard to maintain, so I would still proffered to have it in a separate module, especially since several injector libraries is about to be supported.

**Comment by jakoss** [comment]
I totally get what you mean, but the issue is that i cannot think of a way of implementing addons for ksp plugin. If i do this as a separate module i have to do another processor. But one processor cannot modify existing code. Since injection annotations have to be applies directly to the class - this make this whole endeavor impossible. Do you have an idea how to solve this?

Still, separate module is fine if you have to add new dependencies that users might not want. This is not the case in this implementation. Every injector is pretty much a single class and whole solution does not require any dependency at all. So if we cannot come up with a plugin solution to a processor then we probably need to live with it (or just discard the idea altogether)

**Comment by s0nicyouth** [comment]
How is it implemented in Room? There is 
`// optional - RxJava2 support for Room
    implementation "androidx.room:room-rxjava2:$room_version"
` there for example and they support KSP, so I reckon there should be a way to do so.

**Comment by jakoss** [comment]
This is just implementation module, it adds metadata to classes that then can be processed by the ksp compiler. But room (and i think all other processors) have only single compiler module

**Comment by jakoss** [comment]
I mean - we could add module that will have a single class in which you have to set some value to true if you want injection made - but generating code - it's still compiler module job, no way around that.

MapStruct have injection generating too - built in the main compiler module

**Comment by s0nicyouth** [comment]
But how does it work then if room-compiler doesn't have a dependency on room-rxjava2? At least I can't find any [https://cs.android.com/androidx/platform/frameworks/support/+/androidx-main:room/room-compiler/build.gradle](here).

**Comment by jakoss** [comment]
Look, i just implemented injection for koin without any koin dependency. You can just create `ClassName` with qualified name as string. The `room-rxjava2` is there just so they can introduce some mapping code an so on.

You can have to add annotations, compiler can detect the `Observable` result by a `ClassName`, without need for a dependency. Just like my implementation adds koin annotation without any dependency. But the compiler still has to know about that stuff

**Comment by jakoss** [comment]
I found it in room - they do exactly the same thing, they are generating RxJava-related code in the compiler using just `ClassNames` [here](https://cs.android.com/androidx/platform/frameworks/support/+/androidx-main:room/room-compiler/src/main/kotlin/androidx/room/solver/RxTypes.kt)

**Comment by s0nicyouth** [comment]
I indeed understand that. But I don't get why does one need to include  room-rxjava2 in the dependency list to have support for RxJava then? Actually I just checked their source and there is only 2 helper files there which help to create Flowables.

**Comment by jakoss** [comment]
I guess they are needed there for some reason, but most of the logic stays in compiler :)

**Comment by s0nicyouth** [comment]
> I found it in room - they do exactly the same thing, they are generating RxJava-related code in the compiler using just `ClassNames` [here](https://cs.android.com/androidx/platform/frameworks/support/+/androidx-main:room/room-compiler/src/main/kotlin/androidx/room/solver/RxTypes.kt)

Yeah, you're right, they do the same. Well still don't get why I need an additional module for that then :). I thought there's some tricky way to move it into separate module. If not I suppose no other obstacles here. Thanks for clarification.

**Comment by jakoss** [comment]
I introduced tests on generated code, [here](https://github.com/jakoss/kmapper/commit/a1a443786fbfb30c86cd8c807c6693595a5d8512) you can see an example of that. Does that seem fine for you? It's basically unit test for code generation

**Comment by jakoss** [comment]
@s0nicyouth question, is there a reason you are doing that in testload:
```
implementation("io.github.s0nicyouth:processor_annotations:$kMapperVersion")
implementation("io.github.s0nicyouth:converters:$kMapperVersion")
ksp("io.github.s0nicyouth:processor:$kMapperVersion")
```

instead of 
```
implementation(project(":processor_annotations"))
implementation(project(":converters"))
ksp(project(":processor"))
```

This is raising the "entry bar" a little and I'm not sure what is the benefit here. I'm not experienced in library development, hence the question :)

**Comment by s0nicyouth** [comment]
@jakoss I did that to make sure that changes are mutually compatible in the version rolled out to production basically.
You don't need to run a maven server to do that, maven can just use local directories as a path, you just need to locally publish artifacts. It can be done with
`
./gradlew processor_annotations:publishToMavenLocal
./gradlew publishToMavenLocal
` commands.

**Comment by jakoss** [comment]
Ok, but I have to do that every time I change something in processor? Maybe that can be automated somehow

**Comment by s0nicyouth** [comment]
So far I don't know how to automate it.

**Comment by jakoss** [comment]
> So far I don't know how to automate it.

Ok, problem for another day :)

**Comment by jakoss** [comment]
I think this is not that simple unfortunately to publish to local maven:
```
Execution failed for task ':processor_annotations:signMavenPublication'.
> Cannot perform signing task ':processor_annotations:signMavenPublication' because it has no configured signatory
```

**Comment by s0nicyouth** [comment]
@jakoss You also need to set up credentials basically. You'll need to create pgp keys and publish them to some open service(Ubintu provides one). [Here's a manual](https://central.sonatype.org/publish/requirements/gpg/#signing-a-file)

**Comment by jakoss** [comment]
@s0nicyouth That's what i meant when i was talking about raising the "entry bar". I myself find it very discouraging when i have to do so many things just to make the basic gradle sync in IntelliJ. How many contributors you might loose just because of that? :) Maybe there's another way to make the compatibility check and use normal project dependencies?

**Comment by s0nicyouth** [comment]
It takes around 15 minutes to set it all up once and forget about it. And all of this is still needed to miantain maven relateds libs.
